databases:
  - name: oasobi_production
    databaseName: oasobi_production
    user: oasobi
    region: singapore

services:
  - type: web
    name: oasobi
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oasobi_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
